import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Contact from "./components/Contact";
import Project from "./components/Project";
import Hero from "./components/Hero";
import About from "./components/About";
import Skill from "./components/Skill";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
         <Navbar />
         <Hero />
         <About />
        <Project /> 
        <Skill />
        {children}
        <Contact />
        </body>
    </html>
  );
}
